const http = require('http');
const fs = require('fs');
const path = require('path');
const PORT = process.env.PORT || 3000;
const CSV_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQGQ9SLlcsoIBHN4my5lYcFnpM1vgh4PHTfXIrZ6joyi6vXuB-_fYVlwRDJvRdWEjnYbDlpbaa4PJt0/pub?gid=26648085&single=true&output=csv';
const CONFIG_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQGQ9SLlcsoIBHN4my5lYcFnpM1vgh4PHTfXIrZ6joyi6vXuB-_fYVlwRDJvRdWEjnYbDlpbaa4PJt0/pub?sheet=CONFIGURAÇÃO&output=csv';

const mime = {'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.ico':'image/x-icon'};
function send(res,status,body,type='application/json; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(body)}
function normalize(value){return String(value||'').toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function parseCSV(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(field);field=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(field);field='';if(row.some(v=>String(v).trim()!==''))rows.push(row);row=[]}else field+=ch}if(field.length||row.length){row.push(field);if(row.some(v=>String(v).trim()!==''))rows.push(row)}return rows}
async function fetchCSV(url){const response=await fetch(url,{headers:{'User-Agent':'NOVAORA/1.0'}});if(!response.ok)throw new Error(`Google Sheets CSV HTTP ${response.status}`);return response.text()}
async function products(){const rows=parseCSV(await fetchCSV(CSV_URL));if(!rows.length)return [];const cols=rows[0].map(normalize);const find=names=>{const wanted=names.map(normalize);return cols.findIndex(c=>wanted.some(n=>c===n||c.includes(n)||n.includes(c)))};const idI=find(['id']),nameI=find(['nome do produto','nome','produto','name','title']),priceI=find(['preco venda','preco','price','valor']),imageI=find(['imagem','image','foto','url imagem','image url']),categoryI=find(['categoria','category','cat']),linkI=find(['link','url produto','product url','affiliate link']),descriptionI=find(['descricao','description']);const bannerI=find(['banner']);const value=(r,i)=>i>=0?String(r[i]||'').trim():'';return rows.slice(1).map(r=>({id:value(r,idI),name:value(r,nameI),price:value(r,priceI),image:value(r,imageI),category:value(r,categoryI),link:value(r,linkI),description:value(r,descriptionI),banner:value(r,bannerI)})).filter(p=>p.name||p.price||p.image||p.link||p.banner)}
async function config(){const rows=parseCSV(await fetchCSV(CONFIG_URL));if(!rows.length)return {};let result={};const norm=s=>normalize(s).replace(/[^a-z0-9]/g,'');for(const r of rows){const cells=r.map(v=>String(v||'').trim());if(!cells.length)continue;const key=norm(cells[0]);const value=cells.length>1?cells.slice(1).join(',').trim():'';if(key)result[key]=value}const aliases=['banner','bannerloja','imagembanner','fundobanner','bannerdaloja'];let banner='';for(const a of aliases){if(result[a]){banner=result[a];break}}return {name:result['nomedaloja']||result['nome']||'NOVAORA',slogan:result['slogan']||result['frase']||'',banner:banner}}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host}`);if(url.pathname==='/api/products')return send(res,200,JSON.stringify(await products()));if(url.pathname==='/api/config')return send(res,200,JSON.stringify(await config()));if(url.pathname==='/health')return send(res,200,JSON.stringify({ok:true,store:'NOVAORA',source:'Google Sheets',sheet:'PRODUTOS + CONFIGURAÇÃO'}));let file=url.pathname==='/'?'/index.html':url.pathname;file=path.normalize(file).replace(/^([.][.][\\/])+/, '');const full=path.join(process.cwd(),file);if(!full.startsWith(process.cwd()))return send(res,403,'Forbidden','text/plain; charset=utf-8');fs.readFile(full,(err,data)=>{if(err)return send(res,404,'Not found','text/plain; charset=utf-8');send(res,200,data,mime[path.extname(full).toLowerCase()]||'application/octet-stream')})}catch(e){console.error(e);send(res,500,JSON.stringify({error:'Erro no servidor NOVAORA'}))}});
server.listen(PORT,'0.0.0.0',()=>console.log(`NOVAORA running on port ${PORT}`));