const http = require('http');
const fs = require('fs');
const path = require('path');
const Stripe = require('stripe');
const PORT = process.env.PORT || 3000;
const stripe = process.env.STRIPE_SECRET_KEY ? new Stripe(process.env.STRIPE_SECRET_KEY) : null;
const CSV_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQ6EWYUSyx5Ysm5x7YpWGVmE_tX981oNZM_pe8e2T0QuiseyNV9x4-KIc6pZmldfw/pub?gid=761034080&single=true&output=csv';
const CONFIG_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQ6EWYUSyx5Ysm5x7YpWGVmE_tX981oNZM_pe8e2T0QuiseyNV9x4-KIc6pZmldfw/pub?sheet=CONFIGURA%C3%87%C3%83O&output=csv';
const ORDERS_FILE = path.join(process.cwd(), 'orders.json');
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.ico':'image/x-icon'};
function send(res,status,body,type='application/json; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(body)}
function normalize(v){return String(v||'').toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function key(v){return normalize(v).replace(/[^a-z0-9]/g,'')}
function parseCSV(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(field);field=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(field);field='';if(row.some(v=>String(v).trim()!==''))rows.push(row);row=[]}else field+=ch}if(field.length||row.length){row.push(field);if(row.some(v=>String(v).trim()!==''))rows.push(row)}return rows}
async function fetchCSV(url){const r=await fetch(url,{headers:{'User-Agent':'NOVAORA/1.0'}});if(!r.ok)throw new Error(`Google Sheets CSV HTTP ${r.status}`);return r.text()}
function value(r,i){return i>=0?String(r[i]||'').trim():''}
function imageUrl(raw){let s=String(raw||'').trim();if(!s)return '';try{const u=new URL(s);if(u.hostname==='drive.google.com'){let m=u.pathname.match(/\/file\/d\/([^/]+)/);if(m)return `https://drive.google.com/uc?export=view&id=${m[1]}`;if(u.searchParams.get('id'))return `https://drive.google.com/uc?export=view&id=${u.searchParams.get('id')}`;}}catch(e){}return s}
async function products(){const rows=parseCSV(await fetchCSV(CSV_URL));if(!rows.length)return [];const cols=rows[0].map(normalize);const find=names=>{const wanted=names.map(normalize);return cols.findIndex(c=>wanted.some(n=>c===n||c.includes(n)||n.includes(c)))};const nameI=find(['nome do produto','nome','produto','name','title']),priceI=find(['preco venda','preco','price','valor']),imageI=find(['imagem','image','foto','url imagem','image url']),categoryI=find(['categoria','category','cat']),linkI=find(['link','url produto','product url','affiliate link']),descriptionI=find(['descricao','description']),bannerI=find(['banner']);return rows.slice(1).map(r=>({name:value(r,nameI),price:value(r,priceI),image:imageUrl(value(r,imageI)),category:value(r,categoryI),link:value(r,linkI),description:value(r,descriptionI),banner:imageUrl(value(r,bannerI))})).filter(p=>p.name||p.price||p.image||p.link||p.banner)}
async function config(){const rows=parseCSV(await fetchCSV(CONFIG_URL));if(!rows.length)return {};const out={};const aliases={name:['nomedaloja','nome','loja','storename'],banner:['banner','bannerloja','imagembanner','fundobanner','bannerdaloja','imagemdefundo','fundodaloja'],slogan:['slogan','frase','mensagem']};for(const r of rows){if(r.length<2)continue;const k=key(r[0]);const v=r.slice(1).join(',').trim();for(const [field,names] of Object.entries(aliases)){if(names.includes(k)&&v)out[field]=v}}if(rows.length>=2){const heads=rows[0].map(key), vals=rows[1];for(const [field,names] of Object.entries(aliases)){const i=heads.findIndex(h=>names.includes(h));if(i>=0&&value(vals,i))out[field]=value(vals,i)}}return {name:out.name||'NOVAORA',slogan:out.slogan||'',banner:imageUrl(out.banner||'')}}
function readOrders(){try{return JSON.parse(fs.readFileSync(ORDERS_FILE,'utf8'))}catch(e){return []}}
function saveOrders(orders){fs.writeFileSync(ORDERS_FILE,JSON.stringify(orders,null,2),'utf8')}
function orderId(){return 'NOVA-'+Date.now().toString(36).toUpperCase()}
function collectRaw(req){return new Promise((resolve,reject)=>{const chunks=[];let size=0;req.on('data',c=>{size+=c.length;if(size>2000000){req.destroy();return}chunks.push(c)});req.on('end',()=>resolve(Buffer.concat(chunks)));req.on('error',reject)})}
async function collectBody(req){const raw=await collectRaw(req);return JSON.parse(raw.toString('utf8')||'{}')}
function orderMessage(order){return `*NOVAORA — ENCOMENDA PAGA*\n\nNº: ${order.id}\nNome: ${order.nome}\nTelefone: ${order.telefone}\nEmail: ${order.email}\nMorada: ${order.morada}\n\nProdutos:\n${order.produtos.map(p=>`- ${p.name} x${p.qty} — €${Number(p.unitPrice).toFixed(2)}`).join('\n')}\n\nTotal: €${Number(order.total).toFixed(2)}\nPagamento: ${order.pagamento}\nEstado: PAGO`}
async function sendWhatsApp(order){const token=process.env.WHATSAPP_ACCESS_TOKEN;const phoneId=process.env.WHATSAPP_PHONE_NUMBER_ID;if(!token||!phoneId){console.log('WhatsApp Cloud API ainda não configurado para a encomenda',order.id);return false}const r=await fetch(`https://graph.facebook.com/v23.0/${phoneId}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:'351937216400',type:'text',text:{preview_url:false,body:orderMessage(order)}})});if(!r.ok){console.error('WhatsApp API',r.status,await r.text());return false}return true}
async function createCheckout(data){if(!stripe)throw new Error('Stripe não configurado');const order={id:orderId(),createdAt:new Date().toISOString(),status:'aguarda_pagamento',nome:String(data.nome).slice(0,160),telefone:String(data.telefone).slice(0,40),email:String(data.email).slice(0,200),morada:String(data.morada).slice(0,500),pagamento:'MB WAY via Stripe',total:Number(data.total||0),produtos:Array.isArray(data.produtos)?data.produtos:[]};if(!order.produtos.length||order.total<=0)throw new Error('Encomenda inválida');const session=await stripe.checkout.sessions.create({mode:'payment',payment_method_types:['mb_way'],customer_email:order.email,phone_number_collection:{enabled:true},billing_address_collection:'required',line_items:order.produtos.map(p=>({price_data:{currency:'eur',product_data:{name:String(p.name).slice(0,120)},unit_amount:Math.round(Number(p.unitPrice)*100)},quantity:Math.max(1,Number(p.qty)||1)})),metadata:{order_id:order.id},success_url:`https://lojanovaora.onrender.com/?payment=success&session_id={CHECKOUT_SESSION_ID}`,cancel_url:'https://lojanovaora.onrender.com/?payment=cancelled'});order.stripeSessionId=session.id;const orders=readOrders();orders.push(order);saveOrders(orders);return {url:session.url,orderId:order.id}}
async function handleWebhook(req,res){if(!stripe)return send(res,503,JSON.stringify({error:'Stripe não configurado'}));const raw=await collectRaw(req);const sig=req.headers['stripe-signature'];let event;try{event=stripe.webhooks.constructEvent(raw,sig,process.env.STRIPE_WEBHOOK_SECRET)}catch(e){return send(res,400,JSON.stringify({error:'Webhook inválido'}))}if(event.type==='checkout.session.completed'){const session=event.data.object;const orders=readOrders();const i=orders.findIndex(o=>o.stripeSessionId===session.id);if(i>=0){orders[i].status='pago';orders[i].paidAt=new Date().toISOString();orders[i].paymentIntent=session.payment_intent||'';orders[i].whatsappSent=await sendWhatsApp(orders[i]);saveOrders(orders)}}return send(res,200,JSON.stringify({received:true}))}
async function proxyImage(res,src){try{const u=new URL(src);if(!['http:','https:'].includes(u.protocol))return send(res,400,'Invalid image URL','text/plain; charset=utf-8');const r=await fetch(u,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)return send(res,r.status,'Image unavailable','text/plain; charset=utf-8');const type=r.headers.get('content-type')||'image/jpeg';const buf=Buffer.from(await r.arrayBuffer());res.writeHead(200,{'Content-Type':type,'Cache-Control':'public, max-age=300'});res.end(buf)}catch(e){console.error(e);send(res,502,'Image proxy error','text/plain; charset=utf-8')}}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host}`);if(req.method==='POST'&&url.pathname==='/api/stripe/webhook')return handleWebhook(req,res);if(req.method==='POST'&&url.pathname==='/api/create-checkout'){const data=await collectBody(req);const result=await createCheckout(data);return send(res,200,JSON.stringify({ok:true,...result}))}if(req.method==='POST'&&url.pathname==='/api/orders'){const data=await collectBody(req);const allowed=['MB WAY','Transferência bancária'];if(!data.nome||!data.telefone||!data.email||!data.morada||!Array.isArray(data.produtos)||!data.produtos.length||!allowed.includes(data.pagamento))return send(res,400,JSON.stringify({ok:false,error:'Dados da encomenda incompletos'}));const order={id:orderId(),createdAt:new Date().toISOString(),status:'aguarda_confirmacao_pagamento',nome:String(data.nome).slice(0,160),telefone:String(data.telefone).slice(0,40),email:String(data.email).slice(0,200),morada:String(data.morada).slice(0,500),pagamento:data.pagamento,total:String(data.total||''),produtos:data.produtos};const orders=readOrders();orders.push(order);saveOrders(orders);return send(res,201,JSON.stringify({ok:true,orderId:order.id,status:order.status}));}if(url.pathname==='/api/products')return send(res,200,JSON.stringify(await products()));if(url.pathname==='/api/config')return send(res,200,JSON.stringify(await config()));if(url.pathname==='/api/image'){const src=url.searchParams.get('url');if(!src)return send(res,400,'Missing image URL','text/plain; charset=utf-8');return proxyImage(res,src)}if(url.pathname==='/health')return send(res,200,JSON.stringify({ok:true,store:'NOVAORA',stripe:!!stripe}));let file=url.pathname==='/'?'/index.html':url.pathname;file=path.normalize(file).replace(/^([.][.][\\/])+/, '');const full=path.join(process.cwd(),file);if(!full.startsWith(process.cwd()))return send(res,403,'Forbidden','text/plain; charset=utf-8');fs.readFile(full,(err,data)=>{if(err)return send(res,404,'Not found','text/plain; charset=utf-8');send(res,200,data,mime[path.extname(full).toLowerCase()]||'application/octet-stream')})}catch(e){console.error(e);send(res,500,JSON.stringify({error:e.message||'Erro no servidor NOVAORA'}))}});
server.listen(PORT,'0.0.0.0',()=>console.log(`NOVAORA running on port ${PORT}`));